#!/bin/sh


# mount virtual file systems from /etc/fstab
mount -a

# explicitly creating /dev/pts as it is failing  with fstab
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts || echo "devpts mount failed"



echo "[INFO] Mounted filesystems:"
mount
echo

# Allow kernel messages to finish printing 
sleep 2

exec /sbin/init
