#!/usr/bin/env bash

set -euo pipefail

# ============================================================
# Safe RootFS Cleaner
#
# Purpose:
#   Remove generated binaries, libraries and metadata from the
#   rootfs while preserving configuration/runtime configuration.
#
# Usage:
#   ./scripts/rootfs_safe_clean.sh <ROOTFS_DIR>
#
# Example:
#   ./scripts/rootfs_safe_clean.sh rpi_rootfs
#
# IMPORTANT:
#   This script intentionally does NOT perform:
#
#       rm -rf "$ROOTFS_DIR"/*
#
#   Configuration files/directories are preserved.
# ============================================================

if [ "$#" -ne 1 ]; then
    echo
    echo "Usage:"
    echo
    echo "  $0 <ROOTFS_DIR>"
    echo
    exit 1
fi

ROOTFS_DIR="$(cd "$1" && pwd)"

echo
echo "============================================================"
echo " Safe RootFS Clean"
echo "============================================================"
echo
echo "RootFS:"
echo "  $ROOTFS_DIR"
echo

# ============================================================
# Safety check
# ============================================================

if [ "$ROOTFS_DIR" = "/" ]; then
    echo "[ERROR] Refusing to clean /"
    exit 1
fi

if [ -z "$ROOTFS_DIR" ] || [ ! -d "$ROOTFS_DIR" ]; then
    echo "[ERROR] Invalid rootfs directory:"
    echo "        $ROOTFS_DIR"
    exit 1
fi

# ============================================================
# Directories containing generated binaries/runtime files
#
# These are safe to remove because they are generated package
# content, not configuration.
# ============================================================

REMOVE_DIRS=(
    "bin"
    "sbin"
    "lib"
    "lib64"
    "usr/bin"
    "usr/sbin"
    "usr/lib"
    "usr/lib64"
    "usr/local/bin"
    "usr/local/sbin"
    "usr/local/lib"
)

# ============================================================
# Metadata generated by our package/rootfs builders
# ============================================================

REMOVE_METADATA=(
    ".metadata"
)

# ============================================================
# Display what will be removed
# ============================================================

echo "The following generated directories will be removed:"
echo

for REL_PATH in "${REMOVE_DIRS[@]}"; do
    TARGET="$ROOTFS_DIR/$REL_PATH"

    if [ -e "$TARGET" ] || [ -L "$TARGET" ]; then
        echo "  [REMOVE] /$REL_PATH"
    fi
done

for REL_PATH in "${REMOVE_METADATA[@]}"; do
    TARGET="$ROOTFS_DIR/$REL_PATH"

    if [ -e "$TARGET" ] || [ -L "$TARGET" ]; then
        echo "  [REMOVE] /$REL_PATH"
    fi
done

echo
echo "Configuration files outside these directories will NOT be touched."
echo

# ============================================================
# Confirmation
# ============================================================

read -r -p "Continue with safe rootfs cleanup? [y/N]: " ANSWER

case "$ANSWER" in
    y|Y)
        ;;
    *)
        echo
        echo "[INFO] Cleanup cancelled."
        exit 0
        ;;
esac

echo

# ============================================================
# Remove generated binary/runtime directories
# ============================================================

REMOVE_COUNT=0

for REL_PATH in "${REMOVE_DIRS[@]}"; do
    TARGET="$ROOTFS_DIR/$REL_PATH"

    if [ -e "$TARGET" ] || [ -L "$TARGET" ]; then
        echo "[REMOVE] /$REL_PATH"
        rm -rf -- "$TARGET"
        REMOVE_COUNT=$((REMOVE_COUNT + 1))
    fi
done

# ============================================================
# Remove metadata
# ============================================================

for REL_PATH in "${REMOVE_METADATA[@]}"; do
    TARGET="$ROOTFS_DIR/$REL_PATH"

    if [ -e "$TARGET" ] || [ -L "$TARGET" ]; then
        echo "[REMOVE] /$REL_PATH"
        rm -rf -- "$TARGET"
        REMOVE_COUNT=$((REMOVE_COUNT + 1))
    fi
done

# ============================================================
# Recreate basic directory structure
#
# These are empty directories only. No configuration is created
# or modified.
# ============================================================

mkdir -p \
    "$ROOTFS_DIR/bin" \
    "$ROOTFS_DIR/sbin" \
    "$ROOTFS_DIR/lib" \
    "$ROOTFS_DIR/usr/bin" \
    "$ROOTFS_DIR/usr/sbin" \
    "$ROOTFS_DIR/usr/lib"

# ============================================================
# Summary
# ============================================================

echo
echo "============================================================"
echo " RootFS Safe Clean Complete"
echo "============================================================"
echo
echo "Generated directories removed : $REMOVE_COUNT"
echo
echo "Configuration files preserved."
echo "Metadata removed."
echo "RootFS directory preserved:"
echo "  $ROOTFS_DIR"
echo
echo "============================================================"
