#!/bin/sh

# Fix Dropbear SSH permissions for root user
if [ -d /root/.ssh ]; then
    chown -R root:root /root/.ssh
    chmod 700 /root/.ssh
    chmod 700 /root
    [ -f /root/.ssh/authorized_keys ] && chmod 600 /root/.ssh/authorized_keys
fi
